spring:
  profiles:
    active:
      prod
  mail:
    host: mail.cdleldt.com
    port: 587
    username: support@cdleldt.com
    password: IDon'tNeedPassword#$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
application:
  security:
    jwt:
      secret-key: 5b9e706305ade9af4bb3028b2ab5368ed36842cd68f32c17e0f150256e815ba3
      expiration: 3153600000000
      refresh-token:
        expiration: 3153600000000
